nodeSelector:
  production: worker

config:
  BinderHub:
    base_url: /binder/
    hub_url: https://notebooks.gesis.org/binder/jupyter/

    use_registry: true
    image_prefix: gesiscss/orc-binder-
    build_image: jupyter/repo2docker:9f081a2
    per_repo_quota: 100
    build_node_selector:
      build: workers
    appendix: |
      USER root
      ENV BINDER_URL={binder_url}
      ENV REPO_URL={repo_url}
      RUN cd /tmp \
       && wget -q https://github.com/gesiscss/orc/archive/master.tar.gz -O orc.tar.gz \
       && tar --wildcards -xzf orc.tar.gz --strip 2 */binderhub/appendix\
       && ./appendix/run-appendix \
       && rm -rf orc.tar.gz appendix
      USER $NB_USER

    template_path: /etc/binderhub/templates/binderhub/templates
    #extra_static_path: /etc/binderhub/templates/binderhub/static
    #extra_static_url_prefix: extra_static/

  GitHubRepoProvider:
    # Add banned repositories to the list below
    # They should be strings that will match "^<org-name>/<repo-name>.*"
    banned_specs:
      # e.g. '^org/repo.*'
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*

extraConfig:
  templates: |
    staging = False
    production = True
    site_url = 'https://notebooks{}.gesis.org'.format('-test' if staging else '')
    context = {
        'staging': staging,
        'production': production,
        'version': 'beta',
        # 'shibboleth_entityID': f'{site_url}/shibboleth',
        'home_url': '/',
        'jhub_url': '/hub/',
        'logout_url': '/hub/logout',
        'gesis_login_url': f'{site_url}/Shibboleth.sso/Login?SAMLDS=1&'
                           f'target={site_url}/hub/login&'
                           f'entityID=https%3A%2F%2Fidp.gesis.org%2Fidp%2Fshibboleth',
        'bhub_url': '/binder/',
        'about_url': '/about/',
        'tou_url': '/terms_of_use/',
        'imprint_url': 'https://www.gesis.org/en/institute/imprint/',
        'data_protection_url': 'https://www.gesis.org/en/institute/data-protection/',
        'gesis_url': 'https://www.gesis.org/en/home/',
        'gallery_url': '/gallery/'
        # 'help_url': 'https://www.gesis.org/en/help/',
    }
    context.update({'user': None})
    #context.update({'show_jhub_menu': False})
    c.BinderHub.template_variables = context

resources:
  requests:
    cpu: "0.25"
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 2Gi

service:
  annotations:
    prometheus.io/path: '/binder/metrics'
  type: NodePort
  nodePort: 30081

dind:
  enabled: false

imageCleaner:
  enabled: false

initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=master
      - --depth=1
      - --
      - https://github.com/gesiscss/orc.git
      - /etc/binderhub/templates
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/templates
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/templates

cors: &cors
  allowOrigin: "*"

jupyterhub:
  custom:
    cors: *cors
  hub:
    baseUrl: /binder/jupyter/
    nodeSelector:
      production: worker
    annotations:
      prometheus.io/path: "/binder/jupyter/hub/metrics"
    deploymentStrategy:
      type: RollingUpdate
    db:
      type: postgres
    resources:
      requests:
        cpu: "0.25"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
    extraConfig:
      neverRestart: |
        c.KubeSpawner.extra_pod_config.update({'restart_policy': 'Never'})

  proxy:
    nodeSelector:
      production: worker
    https:
      enabled: false
    service:
      type: NodePort
      nodePorts:
        http: 30082
    chp:
      resources:
        requests:
          cpu: "0.25"
          memory: 512Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  singleuser:
    nodeSelector:
      user: workers
    cpu:
      guarantee: 0.2
      limit: 2
    memory:
      guarantee: 2G
      limit: 8G
    extraEnv:
      # settings for kernel culling
      # to be used in binderhub/appendix/extra_notebook_config.py
      CULL_CONNECTED: '1'
      CULL_TIMEOUT: '900'
      CULL_KERNEL_TIMEOUT: '900'
      CULL_INTERVAL: '60'

  cull:
    # cull every 16 minutes so it is out of phase
    timeout: 900
    every: 960
    # maxAge is 6 hours: 6 * 3600 = 21600
    maxAge: 21600

