apiVersion: v1
kind: ServiceAccount
metadata:
  name: xfs-nfs-provisioner
---
kind: Service
apiVersion: v1
metadata:
  name: xfs-nfs-provisioner
  labels:
    app: xfs-nfs-provisioner
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: xfs-nfs-provisioner
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: xfs-nfs-provisioner
spec:
  selector:
    matchLabels:
      app: xfs-nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xfs-nfs-provisioner
    spec:
      serviceAccount: xfs-nfs-provisioner
      nodeSelector:
        # because of hostPath PVs
        main: worker
      containers:
        - name: xfs-nfs-provisioner
          # https://quay.io/repository/kubernetes_incubator/nfs-provisioner?tag=latest&tab=tags
          image: quay.io/kubernetes_incubator/nfs-provisioner:v2.2.0-k8s1.12
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=orc.external/xfs-nfs"
            - "-enable-xfs-quota=true"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: xfs-nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
#            path: /export
            path: /xfs/nfs