service:
  annotations:
    prometheus.io/scrape: 'false'
  type: NodePort
  nodePort: 30183

# deployment
nodeSelector:
  staging: worker

resources:
  requests:
    cpu: "0.25"
    memory: 512Mi
  limits:
    cpu: "0.5"
    memory: 512Mi

# clone custom binder templates into a volume
initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=binderinjhub
      - --depth=1
      - --
      - https://github.com/gesiscss/orc.git
      - /etc/binderhub/custom
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/custom
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/custom

dind:
  enabled: false

imageCleaner:
  enabled: false

config:
  BinderHub:
    debug: true
    base_url: /jupyter/services/binder/
    hub_url: https://notebooks-test.gesis.org/jupyter/

    use_registry: true
    image_prefix: gesiscss/orc-jhub-binder-staging-
    build_image: jupyter/repo2docker:9766c954
    per_repo_quota: 100
    build_node_selector:
      build: workers
    appendix: |
      USER root
      ENV BINDER_URL={binder_url}
      ENV REPO_URL={repo_url}
      USER $NB_USER
      RUN pip install nbgitpuller
      RUN jupyter serverextension enable --py nbgitpuller --sys-prefix

    template_path: /etc/binderhub/custom/binderhub/templates
    #extra_static_path: /etc/binderhub/custom/binderhub/static
    #extra_static_url_prefix: /extra_static/

    auth_enabled: true

  GitHubRepoProvider:
    # Add banned repositories to the list below
    # They should be strings that will match "^<org-name>/<repo-name>.*"
    banned_specs:
      # e.g. '^org/repo.*'
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*

extraConfig:
  templates: |
    staging = True
    production = False
    site_url = 'https://notebooks{}.gesis.org'.format('-test' if staging else '')
    context = {
        'staging': staging,
        'production': production,
        'version': 'beta',
        # 'shibboleth_entityID': f'{site_url}/shibboleth',
        'home_url': '/',
        'jhub_url': '/jupyter/',
        'gesis_login_url': f'{site_url}/Shibboleth.sso/Login?SAMLDS=1&'
                           f'target={site_url}/hub/login&'
                           f'entityID=https%3A%2F%2Fidp.gesis.org%2Fidp%2Fshibboleth',
        'bhub_url': '/binder/',
        'about_url': '/about/',
        'tou_url': '/terms_of_use/',
        'imprint_url': 'https://www.gesis.org/en/institute/imprint/',
        'data_protection_url': 'https://www.gesis.org/en/institute/data-protection/',
        'gesis_url': 'https://www.gesis.org/en/home/',
        'gallery_url': '/gallery/'
        # 'help_url': 'https://www.gesis.org/en/help/',
    }
    context.update({'active': 'jupyterhub'})
    c.BinderHub.template_variables = context

cors: &cors
  allowOrigin: "*"

jupyterhub:
  custom:
    cors: *cors
  debug:
    enabled: true

  hub:
    service:
      annotations:
        prometheus.io/scrape: 'false'
    baseUrl: /jupyter/
    nodeSelector:
      staging: worker
    image:
      name: gesiscss/k8s-hub-orc
      tag: "21d6428"
    deploymentStrategy:
      type: RollingUpdate
    db:
      type: postgres
    services:
      binder:
        url: http://194.95.75.10:30183
        oauth_redirect_uri: "https://notebooks-test.gesis.org/jupyter/services/binder/oauth_callback"
        oauth_client_id: "binder-oauth-client-staging"
    extraConfig:
      orc: |
        c.JupyterHub.redirect_to_server = False
        c.JupyterHub.bind_url = 'https://notebooks-test.gesis.org/jupyter/'
      templates: |
        c.JupyterHub.template_paths = ['/srv/jhub_custom_templates']
        staging = True
        production = False
        site_url = 'https://notebooks{}.gesis.org'.format('-test' if staging else '')
        context = {
            'staging': staging,
            'production': production,
            'version': 'beta',
            # 'shibboleth_entityID': f'{site_url}/shibboleth',

            'home_url': '/',
            'jhub_url': '/jupyter/',
            # 'logout_url': '/jupyter/hub/logout',
            'gesis_login_url': f'{site_url}/Shibboleth.sso/Login?SAMLDS=1&'
                               f'target={site_url}/hub/login&'
                               f'entityID=https%3A%2F%2Fidp.gesis.org%2Fidp%2Fshibboleth',
            'bhub_url': '/binder/',
            'about_url': '/about/',
            'tou_url': '/terms_of_use/',
            'imprint_url': 'https://www.gesis.org/en/institute/imprint/',
            'data_protection_url': 'https://www.gesis.org/en/institute/data-protection/',
            'gesis_url': 'https://www.gesis.org/en/home/',
            'gallery_url': '/gallery/'
            # 'help_url': 'https://www.gesis.org/en/help/',
        }
        context.update({'active': 'jupyterhub'})
        c.JupyterHub.template_vars = context
      binder: |
        from tornado import gen
        from kubespawner import KubeSpawner

        class BinderSpawner(KubeSpawner):
          banned_images = []
          # allowed_images = []
          def start(self):
            if 'image' in self.user_options and \
              'repo_url' in self.user_options and \
              'token' in self.user_options:
              # binder service sets the image spec via user options
              image = self.user_options['image']
              # NOTE: user can pass any options through API (without using binder) too
              if image in self.banned_images or image.split(':')[0] in self.banned_images:
                self.log.error("Image %s is in banned.", image)
                raise Exception("Image %s is in banned.", image)
              self.repo_url = self.user_options['repo_url'].rstrip('/').rstrip('.git')
              self.ref = image.split(':')[-1]
            else:
              # user starts server without binder form (default)
              # for example via spawn url or by refresing user page when server was stopped
              # launch latest repo in history
              state = self.get_state()
              self.repo_url, self.ref, _ = state['history'][-1]

            #repo_name = self.repo_url.rstrip('/').split('/')[-1]
            repo_dir = '_'.join(reversed(self.repo_url.replace('https://', '').split('/')))
            if self.repo_url.endswith('github.com/gesiscss/data_science_image'):
              self.lifecycle_hooks = {'postStart': {'exec': {'command': ["mkdir", "-p", repo_dir]}}}
            else:
              self.lifecycle_hooks = {'postStart': {'exec': {'command': ["gitpuller", self.repo_url, "master", repo_dir]}}}
            self.notebook_dir = '~/' + repo_dir
            #self.default_url = '/tree/' + repo_dir

            self.extra_pod_config.update({'restart_policy': 'Never'})
            return super().start()

          def get_state(self):
            state_ = self.orm_spawner.state
            # default default_list is only to use when first login
            default_list = [['https://github.com/gesiscss/data_science_image', 'master', 'never']]
            history = state_.get('history', default_list) if state_ else default_list
            state = super().get_state()
            state['history'] = history
            if hasattr(self, 'repo_url') and hasattr(self, 'ref'):
              from datetime import datetime
              e = (self.repo_url, self.ref, datetime.utcnow().strftime("%d.%m.%Y %H:%M"))
              history_ = []
              for h in history:
                if h[0] != e[0]:
                  history_.append(h)
              history_.append(e)
              state['history'] = history_[-10:]  # save last 10 launched images
            if not state['history']:
              state['history'] = default_list
            return state
        c.JupyterHub.spawner_class = BinderSpawner

    resources:
      requests:
        cpu: "0.1"
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi

  proxy:
    nodeSelector:
      staging: worker
    https:
      enabled: false
    service:
      type: NodePort
      nodePorts:
        http: 30180
    chp:
      resources:
        requests:
          cpu: "0.1"
          memory: 256Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  auth:
    type: github
    github:
      clientId: "f2637ba74fe83699b7f5"
      callbackUrl: "https://notebooks-test.gesis.org/jupyter/hub/oauth_callback"
    scopes:
      - "read:user"
    admin:
      users: ['bitnik', 'arnim']

  singleuser:
    nodeSelector:
      user: workers
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser
    storage:
      type: dynamic
      capacity: 15Gi
      extraVolumes:
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
    image:
      name: gesiscss/singleuser-orc
      tag: "r2d-e1b414e1"
    cpu:
      guarantee: 0.1
      limit: 1
    memory:
      guarantee: 512M
      limit: 1G
    extraEnv:
      # settings for kernel culling
      # to be used in binderhub/files/etc/jupyter/jupyter_notebook_config.py
      CULL_CONNECTED: '1'
      CULL_TIMEOUT: '600'
      CULL_KERNEL_TIMEOUT: '600'
      CULL_INTERVAL: '60'

  cull:
    # don't cull authenticated users
    users: false
    # cull every 11 minutes so it is out of phase
    every: 660
    timeout: 600
    # maxAge is 6 hours: 6 * 3600 = 21600
    maxAge: 21600
