service:
  annotations:
    prometheus.io/scrape: 'false'
  type: NodePort
  nodePort: 30183

# deployment
nodeSelector:
  staging: worker

resources:
  requests:
    cpu: "0.25"
    memory: 512Mi
  limits:
    cpu: "0.5"
    memory: 512Mi

# clone custom binder templates into a volume
initContainers:
  - name: git-clone-templates
    image: alpine/git
    args:
      - clone
      - --single-branch
      - --branch=binderinjhub
      - --depth=1
      - --
      - https://github.com/gesiscss/orc.git
      - /etc/binderhub/custom
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: custom-templates
        mountPath: /etc/binderhub/custom
extraVolumes:
  - name: custom-templates
    emptyDir: {}
extraVolumeMounts:
  - name: custom-templates
    mountPath: /etc/binderhub/custom

dind:
  enabled: false

imageCleaner:
  enabled: false

config:
  BinderHub:
    debug: true
    base_url: /jupyter/services/binder/
    hub_url: https://notebooks-test.gesis.org/jupyter/

    use_registry: true
    image_prefix: gesiscss/orc-jhub-binder-staging-
    build_image: jupyter/repo2docker:9766c954
    per_repo_quota: 100
    build_node_selector:
      build: workers
    appendix: |
      USER root
      ENV BINDER_URL={binder_url}
      ENV REPO_URL={repo_url}
      USER $NB_USER
      RUN pip install nbgitpuller
      RUN jupyter serverextension enable --py nbgitpuller --sys-prefix

    template_path: /etc/binderhub/custom/binderhub/templates
    #extra_static_path: /etc/binderhub/custom/binderhub/static
    #extra_static_url_prefix: /extra_static/

    auth_enabled: true

  GitHubRepoProvider:
    # Add banned repositories to the list below
    # They should be strings that will match "^<org-name>/<repo-name>.*"
    banned_specs:
      # e.g. '^org/repo.*'
      - ^ines/spacy-binder.*
      - ^soft4voip/rak.*

extraConfig:
  templates: |
    staging = True
    production = False
    site_url = 'https://notebooks{}.gesis.org'.format('-test' if staging else '')
    context = {
        'staging': staging,
        'production': production,
        'version': 'beta',
        # 'shibboleth_entityID': f'{site_url}/shibboleth',
        'home_url': '/',
        'jhub_url': '/jupyter/',
        'gesis_login_url': f'{site_url}/Shibboleth.sso/Login?SAMLDS=1&'
                           f'target={site_url}/hub/login&'
                           f'entityID=https%3A%2F%2Fidp.gesis.org%2Fidp%2Fshibboleth',
        'bhub_url': '/binder/',
        'about_url': '/about/',
        'tou_url': '/terms_of_use/',
        'imprint_url': 'https://www.gesis.org/en/institute/imprint/',
        'data_protection_url': 'https://www.gesis.org/en/institute/data-protection/',
        'gesis_url': 'https://www.gesis.org/en/home/',
        'gallery_url': '/gallery/'
        # 'help_url': 'https://www.gesis.org/en/help/',
    }
    context.update({'active': 'jupyterhub'})
    c.BinderHub.template_variables = context

cors: &cors
  allowOrigin: "*"

jupyterhub:
  custom:
    cors: *cors
  debug:
    enabled: true

  hub:
    service:
      annotations:
        prometheus.io/scrape: 'false'
    baseUrl: /jupyter/
    nodeSelector:
      staging: worker
    image:
      name: gesiscss/k8s-hub-orc
      tag: "af0da7b8"
    deploymentStrategy:
      type: RollingUpdate
    db:
      type: postgres
    services:
      binder:
        url: http://194.95.75.10:30183
        oauth_redirect_uri: "https://notebooks-test.gesis.org/jupyter/services/binder/oauth_callback"
        oauth_client_id: "binder-oauth-client-staging"
    extraConfig:
      orc: |
        c.Authenticator.shibboleth_logout_url = 'https://notebooks-test.gesis.org/Shibboleth.sso/Logout?return=https://notebooks-test.gesis.org/'
        c.JupyterHub.redirect_to_server = False
        c.JupyterHub.bind_url = 'https://notebooks-test.gesis.org/jupyter/'
        if "cookie_options" in c.JupyterHub.tornado_settings:
          c.JupyterHub.tornado_settings["cookie_options"].update({"secure": True})
        else:
          c.JupyterHub.tornado_settings["cookie_options"] = dict(secure=True)
      templates: |
        c.JupyterHub.template_paths = ['/srv/jhub_custom_templates']
        staging = True
        production = False
        site_url = 'https://notebooks{}.gesis.org'.format('-test' if staging else '')
        context = {
            'staging': staging,
            'production': production,
            'version': 'beta',
            # 'shibboleth_entityID': f'{site_url}/shibboleth',

            'home_url': '/',
            'jhub_url': '/jupyter/',
            # 'logout_url': '/jupyter/hub/logout',
            'gesis_login_url': f'{site_url}/Shibboleth.sso/Login?SAMLDS=1&'
                               f'target={site_url}/hub/login&'
                               f'entityID=https%3A%2F%2Fidp.gesis.org%2Fidp%2Fshibboleth',
            'bhub_url': '/binder/',
            'about_url': '/about/',
            'tou_url': '/terms_of_use/',
            'imprint_url': 'https://www.gesis.org/en/institute/imprint/',
            'data_protection_url': 'https://www.gesis.org/en/institute/data-protection/',
            'gesis_url': 'https://www.gesis.org/en/home/',
            'gallery_url': '/gallery/'
            # 'help_url': 'https://www.gesis.org/en/help/',
        }
        context.update({'active': 'jupyterhub'})
        c.JupyterHub.template_vars = context
      admin_handler: |
        from jupyterhub.handlers.base import BaseHandler
        from jupyterhub.utils import admin_only
        from jupyterhub import orm
        class OrcAdminHandler(BaseHandler):
          """Render the admin page."""
          @admin_only
          async def get(self):
              available = {'name', 'admin', 'running', 'last_activity'}
              default_sort = ['last_activity']
              mapping = {
                  'running': orm.Spawner.server_id,
              }
              for name in available:
                  if name not in mapping:
                      mapping[name] = getattr(orm.User, name)

              default_order = {
                  'name': 'asc',
                  'last_activity': 'desc',
                  'admin': 'desc',
                  'running': 'desc',
              }

              sorts = self.get_arguments('sort') or default_sort
              orders = self.get_arguments('order')

              for bad in set(sorts).difference(available):
                  self.log.warning("ignoring invalid sort: %r", bad)
                  sorts.remove(bad)
              for bad in set(orders).difference({'asc', 'desc'}):
                  self.log.warning("ignoring invalid order: %r", bad)
                  orders.remove(bad)

              # add default sort as secondary
              for s in default_sort:
                  if s not in sorts:
                      sorts.append(s)
              if len(orders) < len(sorts):
                  for col in sorts[len(orders):]:
                      orders.append(default_order[col])
              else:
                  orders = orders[:len(sorts)]

              # this could be one incomprehensible nested list comprehension
              # get User columns
              cols = [ mapping[c] for c in sorts ]
              # get User.col.desc() order objects
              ordered = [ getattr(c, o)() for c, o in zip(cols, orders) ]

              users = self.db.query(orm.User).outerjoin(orm.Spawner).order_by(*ordered)
              users = [ self._user_from_orm(u) for u in users ]
              running = [ u for u in users if u.running ]
              for user in users:
                  auth_state = await user.get_auth_state()
                  auth_state = auth_state or {}
                  setattr(user, 'gn', auth_state.get('Givenname', ''))
                  setattr(user, 'sn', auth_state.get('sn', ''))

              html = self.render_template('admin.html',
                  user=self.get_current_user(),
                  admin_access=self.settings.get('admin_access', False),
                  users=users,
                  running=running,
                  sort={s:o for s,o in zip(sorts, orders)},
              )
              self.finish(html)
        c.JupyterHub.extra_handlers = [(r'/admin_orc', OrcAdminHandler),]
      binder: |
        from tornado import gen
        from kubespawner import KubeSpawner

        class BinderSpawner(KubeSpawner):
          banned_images = []
          # allowed_images = []
          def start(self):
            if 'image' in self.user_options and \
              'repo_url' in self.user_options and \
              'token' in self.user_options:
              # binder service sets the image spec via user options
              image = self.user_options['image']
              # NOTE: user can pass any options through API (without using binder) too
              if image in self.banned_images or image.split(':')[0] in self.banned_images:
                self.log.error("Image %s is in banned.", image)
                raise Exception("Image %s is in banned.", image)
              self.repo_url = self.user_options['repo_url'].rstrip('/').rstrip('.git')
              self.ref = image.split(':')[-1]
            else:
              # user starts server without binder form (default)
              # for example via spawn url or by refresing user page when server was stopped
              # launch latest repo in history
              state = self.get_state()
              self.repo_url, self.ref, _ = state['history'][-1]

            #repo_name = self.repo_url.rstrip('/').split('/')[-1]
            repo_dir = '_'.join(reversed(self.repo_url.replace('https://', '').split('/')))
            if self.repo_url.endswith('github.com/gesiscss/data_science_image'):
              self.lifecycle_hooks = {'postStart': {'exec': {'command': ["mkdir", "-p", repo_dir]}}}
            else:
              self.lifecycle_hooks = {'postStart': {'exec': {'command': ["gitpuller", self.repo_url, "master", repo_dir]}}}
            self.notebook_dir = '~/' + repo_dir
            #self.default_url = '/tree/' + repo_dir

            self.extra_pod_config.update({'restart_policy': 'Never'})
            return super().start()

          def get_state(self):
            state_ = self.orm_spawner.state
            # default default_list is only to use when first login
            default_list = [['https://github.com/gesiscss/data_science_image', 'master', 'never']]
            history = state_.get('history', default_list) if state_ else default_list
            state = super().get_state()
            state['history'] = history
            if hasattr(self, 'repo_url') and hasattr(self, 'ref'):
              from datetime import datetime
              e = (self.repo_url, self.ref, datetime.utcnow().strftime("%d.%m.%Y %H:%M"))
              history_ = []
              for h in history:
                if h[0] != e[0]:
                  history_.append(h)
              history_.append(e)
              state['history'] = history_[-10:]  # save last 10 launched images
            if not state['history']:
              state['history'] = default_list
            return state
        c.JupyterHub.spawner_class = BinderSpawner

    resources:
      requests:
        cpu: "0.1"
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi

  proxy:
    nodeSelector:
      staging: worker
    https:
      enabled: false
    service:
      type: NodePort
      nodePorts:
        http: 30180
    chp:
      resources:
        requests:
          cpu: "0.1"
          memory: 256Mi
        limits:
          cpu: "0.5"
          memory: 512Mi

  auth:
    type: custom
    custom:
      className: "jhub_shibboleth_auth.shibboleth_auth.ShibbolethAuthenticator"
    admin:
      access: true
      users: ['kenan.erdogan@gesis.org', 'arnim.bleier@gesis.org']
    state:
      enabled: true

  singleuser:
    nodeSelector:
      user: workers
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser
    storage:
      type: dynamic
      capacity: 15Gi
      extraVolumes:
        - name: etc-jupyter
          configMap:
            name: user-etc-jupyter
      extraVolumeMounts:
        - name: etc-jupyter
          mountPath: /etc/jupyter
    image:
      name: gesiscss/singleuser-orc
      tag: "r2d-e1b414e1"
    cpu:
      guarantee: 0.1
      limit: 1
    memory:
      guarantee: 512M
      limit: 1G
    extraEnv:
      # settings for kernel culling
      # to be used in binderhub/files/etc/jupyter/jupyter_notebook_config.py
      CULL_CONNECTED: '1'
      CULL_TIMEOUT: '600'
      CULL_KERNEL_TIMEOUT: '600'
      CULL_INTERVAL: '60'

  cull:
    # don't cull authenticated users
    users: false
    # cull every 11 minutes so it is out of phase
    every: 660
    timeout: 600
    # maxAge is 6 hours: 6 * 3600 = 21600
    maxAge: 21600
